// This file was automatically generated.  Do not modify.

'use strict';

goog.provide('Blockly.Msg.sl');

goog.require('Blockly.Msg');

Blockly.Msg.ADD_COMMENT = "Dodaj komentar";
Blockly.Msg.CHANGE_VALUE_TITLE = "Spremeni vrednost:";
Blockly.Msg.CLEAN_UP = "Ponastavi kocke";
Blockly.Msg.COLLAPSE_ALL = "Skrči kocke";
Blockly.Msg.COLLAPSE_BLOCK = "Skrči kocko";
Blockly.Msg.COLOUR_BLEND_COLOUR1 = "barva 1";
Blockly.Msg.COLOUR_BLEND_COLOUR2 = "barva 2";
Blockly.Msg.COLOUR_BLEND_HELPURL = "http://meyerweb.com/eric/tools/color-blend/";
Blockly.Msg.COLOUR_BLEND_RATIO = "razmerje";
Blockly.Msg.COLOUR_BLEND_TITLE = "mešanica";
Blockly.Msg.COLOUR_BLEND_TOOLTIP = "Zmeša dve barvi v danem razmerju (0.0 - 1.0).";
Blockly.Msg.COLOUR_PICKER_HELPURL = "https://en.wikipedia.org/wiki/Color";
Blockly.Msg.COLOUR_PICKER_TOOLTIP = "Izberi barvo s palete.";
Blockly.Msg.COLOUR_RANDOM_HELPURL = "http://randomcolour.com";  // untranslated
Blockly.Msg.COLOUR_RANDOM_TITLE = "naključna barva";
Blockly.Msg.COLOUR_RANDOM_TOOLTIP = "Izbere naključno barvo.";
Blockly.Msg.COLOUR_RGB_BLUE = "modra";
Blockly.Msg.COLOUR_RGB_GREEN = "zelena";
Blockly.Msg.COLOUR_RGB_HELPURL = "http://www.december.com/html/spec/colorper.html";
Blockly.Msg.COLOUR_RGB_RED = "rdeča";
Blockly.Msg.COLOUR_RGB_TITLE = "določena barva";
Blockly.Msg.COLOUR_RGB_TOOLTIP = "Ustvari barvo z določeno količino rdeče, zelene in modre. Vse vrednosti morajo biti med 0 in 100.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_HELPURL = "https://github.com/google/blockly/wiki/Loops#loop-termination-blocks";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_BREAK = "izstopi iz zanke";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_OPERATOR_CONTINUE = "nadaljuj z naslednjo ponovitvijo zanke";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_BREAK = "Izstopi iz trenutne zanke.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_TOOLTIP_CONTINUE = "Preskoči preostanek te zanke in nadaljuje z naslednjo ponovitvijo.";
Blockly.Msg.CONTROLS_FLOW_STATEMENTS_WARNING = "Pozor: To kocko lahko uporabiš samo znotraj zanke.";
Blockly.Msg.CONTROLS_FOREACH_HELPURL = "https://github.com/google/blockly/wiki/Loops#for-each";
Blockly.Msg.CONTROLS_FOREACH_TITLE = "za vsak element %1 v seznamu %2";
Blockly.Msg.CONTROLS_FOREACH_TOOLTIP = "Za vsak element v seznamu, nastavi spremenljivko '%1' na ta element. Pri tem se izvedejo določene kocke.";
Blockly.Msg.CONTROLS_FOR_HELPURL = "https://github.com/google/blockly/wiki/Loops#count-with";
Blockly.Msg.CONTROLS_FOR_TITLE = "štej s/z %1 od %2 do %3 s korakom %4";
Blockly.Msg.CONTROLS_FOR_TOOLTIP = "Vrednost spremenljivke '%1' se spreminja od začetnega števila do končnega števila, z določenim korakom. Pri tem se izvedejo določene kocke.";
Blockly.Msg.CONTROLS_IF_ELSEIF_TOOLTIP = "Dodaj pogoj »če« kocki.";
Blockly.Msg.CONTROLS_IF_ELSE_TOOLTIP = "Dodaj končni pogoj »če« kocki.";
Blockly.Msg.CONTROLS_IF_HELPURL = "https://github.com/google/blockly/wiki/IfElse";
Blockly.Msg.CONTROLS_IF_IF_TOOLTIP = "Dodaj, odstrani ali spremeni vrstni red odsekov za ponovno nastavitev »če« kocke.";
Blockly.Msg.CONTROLS_IF_MSG_ELSE = "sicer";
Blockly.Msg.CONTROLS_IF_MSG_ELSEIF = "sicer če";
Blockly.Msg.CONTROLS_IF_MSG_IF = "če";
Blockly.Msg.CONTROLS_IF_TOOLTIP_1 = "Če je vrednost resnična, izvedi določene kocke.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_2 = "Če je vrednost resnična, izvedi prvo skupino kock. Sicer izvedi drugo skupino kock.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_3 = "Če je prva vrednost resnična, izvedi prvo skupino kock. Sicer, če je resnična druga vrednost, izvedi drugo skupino kock.";
Blockly.Msg.CONTROLS_IF_TOOLTIP_4 = "Če je prva vrednost resnična, izvedi prvo skupino kock. Sicer, če je resnična druga vrednost, izvedi drugo skupino kock. Če nobena izmed vrednosti ni resnična, izvedi zadnjo skupino kock.";
Blockly.Msg.CONTROLS_REPEAT_HELPURL = "https://en.wikipedia.org/wiki/For_loop";
Blockly.Msg.CONTROLS_REPEAT_INPUT_DO = "izvedi";
Blockly.Msg.CONTROLS_REPEAT_TITLE = "ponavljaj %1 krat";
Blockly.Msg.CONTROLS_REPEAT_TOOLTIP = "Kocke se izvedejo večkrat.";
Blockly.Msg.CONTROLS_WHILEUNTIL_HELPURL = "https://github.com/google/blockly/wiki/Loops#repeat";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_UNTIL = "ponavljaj dokler";
Blockly.Msg.CONTROLS_WHILEUNTIL_OPERATOR_WHILE = "ponavljaj";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_UNTIL = "Kocke se izvajajo dokler je vrednost neresnična.";
Blockly.Msg.CONTROLS_WHILEUNTIL_TOOLTIP_WHILE = "Kocke se izvajajo dokler je vrednost resnična.";
Blockly.Msg.DELETE_ALL_BLOCKS = "Izbrišem vseh %1 kock?";
Blockly.Msg.DELETE_BLOCK = "Izbriši kocko";
Blockly.Msg.DELETE_VARIABLE = "Izbriši spremenljivko »%1«";
Blockly.Msg.DELETE_VARIABLE_CONFIRMATION = "Izbrišem %1 uporab spremenljivke »%2«?";
Blockly.Msg.DELETE_X_BLOCKS = "Izbriši kocke";
Blockly.Msg.DISABLE_BLOCK = "Onemogoči kocko";
Blockly.Msg.DUPLICATE_BLOCK = "Podvoji";
Blockly.Msg.ENABLE_BLOCK = "Omogoči kocko";
Blockly.Msg.EXPAND_ALL = "Razširi kocke";
Blockly.Msg.EXPAND_BLOCK = "Razširi kocko";
Blockly.Msg.EXTERNAL_INPUTS = "Vnosi zunaj";
Blockly.Msg.HELP = "Pomoč";
Blockly.Msg.INLINE_INPUTS = "Vnosi v vrsti";
Blockly.Msg.LISTS_CREATE_EMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-empty-list";
Blockly.Msg.LISTS_CREATE_EMPTY_TITLE = "ustvari prazen seznam";
Blockly.Msg.LISTS_CREATE_EMPTY_TOOLTIP = "Vrne seznam, dolžine 0, ki ne vsebuje nobenih podatkov.";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TITLE_ADD = "seznam";
Blockly.Msg.LISTS_CREATE_WITH_CONTAINER_TOOLTIP = "Doda, odstrani ali spremeni vrstni red elementov tega seznama.";
Blockly.Msg.LISTS_CREATE_WITH_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg.LISTS_CREATE_WITH_INPUT_WITH = "ustvari seznam s/z";
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TOOLTIP = "Doda element seznamu.";
Blockly.Msg.LISTS_CREATE_WITH_TOOLTIP = "Ustvari seznam s poljubnim številom elementov.";
Blockly.Msg.LISTS_GET_INDEX_FIRST = "prvo mesto";
Blockly.Msg.LISTS_GET_INDEX_FROM_END = "mesto št. od konca";
Blockly.Msg.LISTS_GET_INDEX_FROM_START = "št.";
Blockly.Msg.LISTS_GET_INDEX_GET = "vrni";
Blockly.Msg.LISTS_GET_INDEX_GET_REMOVE = "odstrani in vrni";
Blockly.Msg.LISTS_GET_INDEX_LAST = "zadnje mesto";
Blockly.Msg.LISTS_GET_INDEX_RANDOM = "naključno mesto";
Blockly.Msg.LISTS_GET_INDEX_REMOVE = "odstrani";
Blockly.Msg.LISTS_GET_INDEX_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FIRST = "Vrne prvi element seznama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_FROM = "Vrne element na določenem mestu v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_LAST = "Vrne zadnji element seznama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_RANDOM = "Vrne naključni element seznama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FIRST = "Odstrani in vrne prvi element seznama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_FROM = "Odstrani in vrne element na določenem mestu v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_LAST = "Odstrani in vrne zadnji element seznama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_GET_REMOVE_RANDOM = "Odstrani in vrne naključni element seznama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FIRST = "Odstrani prvi element seznama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_FROM = "Odstrani element na določenem mestu v seznamu.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_LAST = "Odstrani zadnji element seznama.";
Blockly.Msg.LISTS_GET_INDEX_TOOLTIP_REMOVE_RANDOM = "Odstrani naključni element seznama.";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_END = "do mesta št. od konca";
Blockly.Msg.LISTS_GET_SUBLIST_END_FROM_START = "do mesta št.";
Blockly.Msg.LISTS_GET_SUBLIST_END_LAST = "do zadnjega mesta";
Blockly.Msg.LISTS_GET_SUBLIST_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-a-sublist";
Blockly.Msg.LISTS_GET_SUBLIST_START_FIRST = "ustvari podseznam od prvega mesta";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_END = "ustvari podseznam od mesta št. od konca";
Blockly.Msg.LISTS_GET_SUBLIST_START_FROM_START = "ustvari podseznam od mesta št.";
Blockly.Msg.LISTS_GET_SUBLIST_TAIL = "";  // untranslated
Blockly.Msg.LISTS_GET_SUBLIST_TOOLTIP = "Ustvari nov seznam, kot kopijo določenega dela seznama.";
Blockly.Msg.LISTS_INDEX_FROM_END_TOOLTIP = "Zadnji element je št. %1.";
Blockly.Msg.LISTS_INDEX_FROM_START_TOOLTIP = "Prvi element je št. %1.";
Blockly.Msg.LISTS_INDEX_OF_FIRST = "najdi prvo pojavitev elementa";
Blockly.Msg.LISTS_INDEX_OF_HELPURL = "https://github.com/google/blockly/wiki/Lists#getting-items-from-a-list";
Blockly.Msg.LISTS_INDEX_OF_LAST = "najdi zadnjo pojavitev elementa";
Blockly.Msg.LISTS_INDEX_OF_TOOLTIP = "Vrne mesto (indeks) prve/zadnje pojavitve elementa v seznamu. Če elementa ne najde, vrne %1.";
Blockly.Msg.LISTS_INLIST = "v seznamu";
Blockly.Msg.LISTS_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Lists#is-empty";
Blockly.Msg.LISTS_ISEMPTY_TITLE = "%1 je prazen";
Blockly.Msg.LISTS_ISEMPTY_TOOLTIP = "Vrne resnično, če je seznam prazen.";
Blockly.Msg.LISTS_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Lists#length-of";
Blockly.Msg.LISTS_LENGTH_TITLE = "dolžina %1";
Blockly.Msg.LISTS_LENGTH_TOOLTIP = "Vrne dolžino seznama.";
Blockly.Msg.LISTS_REPEAT_HELPURL = "https://github.com/google/blockly/wiki/Lists#create-list-with";
Blockly.Msg.LISTS_REPEAT_TITLE = "ustvari seznam z elementom %1, ki se ponovi %2 krat";
Blockly.Msg.LISTS_REPEAT_TOOLTIP = "Ustvari seznam z danim elementom, ki se poljubno mnogo krat ponovi.";
Blockly.Msg.LISTS_SET_INDEX_HELPURL = "https://github.com/google/blockly/wiki/Lists#in-list--set";
Blockly.Msg.LISTS_SET_INDEX_INPUT_TO = "element";
Blockly.Msg.LISTS_SET_INDEX_INSERT = "vstavi na";
Blockly.Msg.LISTS_SET_INDEX_SET = "nastavi na";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FIRST = "Vstavi element na začetek seznama.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_FROM = "Vstavi element na določeno mesto v seznamu.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_LAST = "Doda element na konec seznama.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_INSERT_RANDOM = "Vstavi element na naključno mesto v seznamu.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FIRST = "Nastavi prvi element seznama.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_FROM = "Nastavi element na določenem mestu v seznamu.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_LAST = "Nastavi zadnji element seznama.";
Blockly.Msg.LISTS_SET_INDEX_TOOLTIP_SET_RANDOM = "Nastavi naključni element seznama.";
Blockly.Msg.LISTS_SORT_HELPURL = "https://github.com/google/blockly/wiki/Lists#sorting-a-list";
Blockly.Msg.LISTS_SORT_ORDER_ASCENDING = "naraščajoče";
Blockly.Msg.LISTS_SORT_ORDER_DESCENDING = "padajoče";
Blockly.Msg.LISTS_SORT_TITLE = "uredi %1 %2 %3";
Blockly.Msg.LISTS_SORT_TOOLTIP = "Uredi kopijo seznama.";
Blockly.Msg.LISTS_SORT_TYPE_IGNORECASE = "abecedno, brez velikosti črk";
Blockly.Msg.LISTS_SORT_TYPE_NUMERIC = "številčno";
Blockly.Msg.LISTS_SORT_TYPE_TEXT = "abecedno";
Blockly.Msg.LISTS_SPLIT_HELPURL = "https://github.com/google/blockly/wiki/Lists#splitting-strings-and-joining-lists";
Blockly.Msg.LISTS_SPLIT_LIST_FROM_TEXT = "ustvari seznam iz besedila";
Blockly.Msg.LISTS_SPLIT_TEXT_FROM_LIST = "ustvari besedilo iz seznama";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_JOIN = "Združi seznam besedil v eno besedilo, ločeno z ločilom.";
Blockly.Msg.LISTS_SPLIT_TOOLTIP_SPLIT = "Razdruži besedilo v seznam besedil. Za razdruževanje besedila uporabi ločilo.";
Blockly.Msg.LISTS_SPLIT_WITH_DELIMITER = "z ločilom";
Blockly.Msg.LOGIC_BOOLEAN_FALSE = "neresnično";
Blockly.Msg.LOGIC_BOOLEAN_HELPURL = "https://github.com/google/blockly/wiki/Logic#values";
Blockly.Msg.LOGIC_BOOLEAN_TOOLTIP = "Vrne resnično ali neresnično.";
Blockly.Msg.LOGIC_BOOLEAN_TRUE = "resnično";
Blockly.Msg.LOGIC_COMPARE_HELPURL = "https://en.wikipedia.org/wiki/Inequality_(mathematics)";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_EQ = "Vrne resnično, če sta vnosa enaka.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GT = "Vrne resnično, če je prvi vnos večji od drugega.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_GTE = "Vrne resnično, če je prvi vnos večji ali enak drugemu.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LT = "Vrne resnično, če je prvi vnos manjši od drugega.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_LTE = "Vrne resnično, če je prvi vnos manjši ali enak drugemu.";
Blockly.Msg.LOGIC_COMPARE_TOOLTIP_NEQ = "Vrne resnično, če vnosa nista enaka.";
Blockly.Msg.LOGIC_NEGATE_HELPURL = "https://github.com/google/blockly/wiki/Logic#not";
Blockly.Msg.LOGIC_NEGATE_TITLE = "ne %1";
Blockly.Msg.LOGIC_NEGATE_TOOLTIP = "Vrne resnično, če je vnos neresničen. Vrne neresnično, če je vnos resničen.";
Blockly.Msg.LOGIC_NULL = "prazno";
Blockly.Msg.LOGIC_NULL_HELPURL = "https://en.wikipedia.org/wiki/Nullable_type";
Blockly.Msg.LOGIC_NULL_TOOLTIP = "Vrne prazno.";
Blockly.Msg.LOGIC_OPERATION_AND = "in";
Blockly.Msg.LOGIC_OPERATION_HELPURL = "https://github.com/google/blockly/wiki/Logic#logical-operations";
Blockly.Msg.LOGIC_OPERATION_OR = "ali";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_AND = "Vrne resnično, če sta oba vnosa resnična.";
Blockly.Msg.LOGIC_OPERATION_TOOLTIP_OR = "Vrne resnično, če je vsaj eden od vnosov resničen.";
Blockly.Msg.LOGIC_TERNARY_CONDITION = "test";
Blockly.Msg.LOGIC_TERNARY_HELPURL = "https://en.wikipedia.org/wiki/%3F:";
Blockly.Msg.LOGIC_TERNARY_IF_FALSE = "če neresnično";
Blockly.Msg.LOGIC_TERNARY_IF_TRUE = "če resnično";
Blockly.Msg.LOGIC_TERNARY_TOOLTIP = "Preveri pogoj v »testu«. Če je pogoj resničen, potem vrne vrednost »če resnično«; sicer vrne vrednost »če neresnično«.";
Blockly.Msg.MATH_ADDITION_SYMBOL = "+";
Blockly.Msg.MATH_ARITHMETIC_HELPURL = "https://en.wikipedia.org/wiki/Arithmetic";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_ADD = "Vrne vsoto dveh števil.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_DIVIDE = "Vrne kvocient dveh števil.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MINUS = "Vrne razliko dveh števil.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_MULTIPLY = "Vrne zmnožek dveh števil.";
Blockly.Msg.MATH_ARITHMETIC_TOOLTIP_POWER = "Vrne prvo število na potenco drugega števila.";
Blockly.Msg.MATH_CHANGE_HELPURL = "https://en.wikipedia.org/wiki/Programming_idiom#Incrementing_a_counter";
Blockly.Msg.MATH_CHANGE_TITLE = "spremeni %1 za %2";
Blockly.Msg.MATH_CHANGE_TOOLTIP = "Prišteje število k spremenljivki '%1'.";
Blockly.Msg.MATH_CONSTANT_HELPURL = "https://en.wikipedia.org/wiki/Mathematical_constant";
Blockly.Msg.MATH_CONSTANT_TOOLTIP = "Vrne eno izmed običajnih konstant: π (3.141…), e (2.718…), φ (1.618…), sqrt(2) (1.414…), sqrt(½) (0.707…), ali ∞ (neskončno).";
Blockly.Msg.MATH_CONSTRAIN_HELPURL = "https://en.wikipedia.org/wiki/Clamping_%28graphics%29";
Blockly.Msg.MATH_CONSTRAIN_TITLE = "omeji %1 na najmanj %2 in največ %3";
Blockly.Msg.MATH_CONSTRAIN_TOOLTIP = "Omeji število, da bo med določenima (vključenima) mejama.";
Blockly.Msg.MATH_DIVISION_SYMBOL = "÷";
Blockly.Msg.MATH_IS_DIVISIBLE_BY = "je deljivo s/z";
Blockly.Msg.MATH_IS_EVEN = "je sodo";
Blockly.Msg.MATH_IS_NEGATIVE = "je negativno";
Blockly.Msg.MATH_IS_ODD = "je liho";
Blockly.Msg.MATH_IS_POSITIVE = "je pozitivno";
Blockly.Msg.MATH_IS_PRIME = "je praštevilo";
Blockly.Msg.MATH_IS_TOOLTIP = "Preveri, če je število sodo, liho, praštevilo, celo, pozitivno, negativno ali, če je deljivo z določenim številom. Vrne resnično ali neresnično.";
Blockly.Msg.MATH_IS_WHOLE = "je celo";
Blockly.Msg.MATH_MODULO_HELPURL = "https://en.wikipedia.org/wiki/Modulo_operation";
Blockly.Msg.MATH_MODULO_TITLE = "ostanek pri %1 ÷ %2";
Blockly.Msg.MATH_MODULO_TOOLTIP = "Vrne ostanek pri deljenju dveh števil.";
Blockly.Msg.MATH_MULTIPLICATION_SYMBOL = "×";
Blockly.Msg.MATH_NUMBER_HELPURL = "https://en.wikipedia.org/wiki/Number";
Blockly.Msg.MATH_NUMBER_TOOLTIP = "Število.";
Blockly.Msg.MATH_ONLIST_HELPURL = "";  // untranslated
Blockly.Msg.MATH_ONLIST_OPERATOR_AVERAGE = "povprečje seznama";
Blockly.Msg.MATH_ONLIST_OPERATOR_MAX = "maksimum seznama";
Blockly.Msg.MATH_ONLIST_OPERATOR_MEDIAN = "mediana seznama";
Blockly.Msg.MATH_ONLIST_OPERATOR_MIN = "minimum seznama";
Blockly.Msg.MATH_ONLIST_OPERATOR_MODE = "modus seznama";
Blockly.Msg.MATH_ONLIST_OPERATOR_RANDOM = "naključni element seznama";
Blockly.Msg.MATH_ONLIST_OPERATOR_STD_DEV = "standardni odklon seznama";
Blockly.Msg.MATH_ONLIST_OPERATOR_SUM = "vsota seznama";
Blockly.Msg.MATH_ONLIST_TOOLTIP_AVERAGE = "Vrne povprečje (aritmetično sredino) števil na seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MAX = "Vrne največje število na seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MEDIAN = "Vrne mediano števil na seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MIN = "Vrne najmanjše število na seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_MODE = "Vrne seznam najpogostejšega elementa(-ov) na seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_RANDOM = "Vrne naključno število izmed števil na seznamu.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_STD_DEV = "Vrne standardni odklon seznama.";
Blockly.Msg.MATH_ONLIST_TOOLTIP_SUM = "Vrne vsoto vseh števil na seznamu.";
Blockly.Msg.MATH_POWER_SYMBOL = "^";
Blockly.Msg.MATH_RANDOM_FLOAT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_FLOAT_TITLE_RANDOM = "naključni ulomek";
Blockly.Msg.MATH_RANDOM_FLOAT_TOOLTIP = "Vrne naključni ulomek med (vključno) 0.0 in 1.0 (izključno).";
Blockly.Msg.MATH_RANDOM_INT_HELPURL = "https://en.wikipedia.org/wiki/Random_number_generation";
Blockly.Msg.MATH_RANDOM_INT_TITLE = "naključno število med %1 in %2";
Blockly.Msg.MATH_RANDOM_INT_TOOLTIP = "Vrne naključno število med dvema določenima mejama, vključno z mejama.";
Blockly.Msg.MATH_ROUND_HELPURL = "https://en.wikipedia.org/wiki/Rounding";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUND = "zaokroži";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDDOWN = "zaokroži navzdol";
Blockly.Msg.MATH_ROUND_OPERATOR_ROUNDUP = "zaokroži navzgor";
Blockly.Msg.MATH_ROUND_TOOLTIP = "Zaokroži število navzgor ali navzdol.";
Blockly.Msg.MATH_SINGLE_HELPURL = "https://en.wikipedia.org/wiki/Square_root";
Blockly.Msg.MATH_SINGLE_OP_ABSOLUTE = "absolutno";
Blockly.Msg.MATH_SINGLE_OP_ROOT = "kvadratni koren";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ABS = "Vrne absolutno vrednost števila.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_EXP = "Vrne e na potenco števila.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LN = "Vrne naravni logaritem števila.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_LOG10 = "Vrne desetiški logaritem števila.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_NEG = "Vrne negacijo števila.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_POW10 = "Vrne 10 na potenco števila.";
Blockly.Msg.MATH_SINGLE_TOOLTIP_ROOT = "Vrne kvadratni koren števila.";
Blockly.Msg.MATH_SUBTRACTION_SYMBOL = "-";
Blockly.Msg.MATH_TRIG_ACOS = "acos";
Blockly.Msg.MATH_TRIG_ASIN = "asin";
Blockly.Msg.MATH_TRIG_ATAN = "atan";
Blockly.Msg.MATH_TRIG_COS = "cos";
Blockly.Msg.MATH_TRIG_HELPURL = "https://en.wikipedia.org/wiki/Trigonometric_functions";
Blockly.Msg.MATH_TRIG_SIN = "sin";
Blockly.Msg.MATH_TRIG_TAN = "tan";
Blockly.Msg.MATH_TRIG_TOOLTIP_ACOS = "Vrne arkus kosinus števila.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ASIN = "Vrne arkus sinus števila.";
Blockly.Msg.MATH_TRIG_TOOLTIP_ATAN = "Vrne arkus tangens števila.";
Blockly.Msg.MATH_TRIG_TOOLTIP_COS = "Vrne kosinus kota v stopinjah (ne radianih).";
Blockly.Msg.MATH_TRIG_TOOLTIP_SIN = "Vrne sinus kota v stopinjah (ne radianih).";
Blockly.Msg.MATH_TRIG_TOOLTIP_TAN = "Vrne tangens kota v stopinjah (ne radianih).";
Blockly.Msg.NEW_VARIABLE = "Ustvari spremenljivko ...";
Blockly.Msg.NEW_VARIABLE_TITLE = "Ime nove spremenljivke:";
Blockly.Msg.ORDINAL_NUMBER_SUFFIX = "";  // untranslated
Blockly.Msg.PROCEDURES_ALLOW_STATEMENTS = "dovoli korake";
Blockly.Msg.PROCEDURES_BEFORE_PARAMS = "s/z:";
Blockly.Msg.PROCEDURES_CALLNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Subroutine";
Blockly.Msg.PROCEDURES_CALLNORETURN_TOOLTIP = "Izvede uporabniško funkcijo '%1'.";
Blockly.Msg.PROCEDURES_CALLRETURN_HELPURL = "https://en.wikipedia.org/wiki/Subroutine";
Blockly.Msg.PROCEDURES_CALLRETURN_TOOLTIP = "Izvede uporabniško funkcijo '%1' in uporabi njen izhod.";
Blockly.Msg.PROCEDURES_CALL_BEFORE_PARAMS = "s/z:";
Blockly.Msg.PROCEDURES_CREATE_DO = "Ustvari '%1'";
Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT = "Opišite funkcijo ...";
Blockly.Msg.PROCEDURES_DEFNORETURN_DO = "";  // untranslated
Blockly.Msg.PROCEDURES_DEFNORETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE = "nekaj";
Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE = "izvedi";
Blockly.Msg.PROCEDURES_DEFNORETURN_TOOLTIP = "Ustvari funkcijo brez izhoda.";
Blockly.Msg.PROCEDURES_DEFRETURN_HELPURL = "https://en.wikipedia.org/wiki/Procedure_%28computer_science%29";
Blockly.Msg.PROCEDURES_DEFRETURN_RETURN = "vrni";
Blockly.Msg.PROCEDURES_DEFRETURN_TOOLTIP = "Ustvari funkcijo z izhodom.";
Blockly.Msg.PROCEDURES_DEF_DUPLICATE_WARNING = "Pozor: Ta funkcija ima podvojene parametre.";
Blockly.Msg.PROCEDURES_HIGHLIGHT_DEF = "Označi definicijo funkcije";
Blockly.Msg.PROCEDURES_IFRETURN_HELPURL = "http://c2.com/cgi/wiki?GuardClause";
Blockly.Msg.PROCEDURES_IFRETURN_TOOLTIP = "Če je vrednost resnična, vrne drugo vrednost.";
Blockly.Msg.PROCEDURES_IFRETURN_WARNING = "Pozor: To kocko lahko uporabiš samo znotraj definicije funkcije.";
Blockly.Msg.PROCEDURES_MUTATORARG_TITLE = "ime vnosa:";
Blockly.Msg.PROCEDURES_MUTATORARG_TOOLTIP = "Funkciji doda vnos.";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TITLE = "vnosi";
Blockly.Msg.PROCEDURES_MUTATORCONTAINER_TOOLTIP = "Doda, odstrani ali spremeni vrstni red vnosov te funkcije.";
Blockly.Msg.REDO = "Ponovi";
Blockly.Msg.REMOVE_COMMENT = "Odstrani komentar";
Blockly.Msg.RENAME_VARIABLE = "Preimenuj spremenljivko...";
Blockly.Msg.RENAME_VARIABLE_TITLE = "Preimenuj vse spremenljivke '%1' v:";
Blockly.Msg.TEXT_APPEND_APPENDTEXT = "dodaj besedilo";
Blockly.Msg.TEXT_APPEND_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";
Blockly.Msg.TEXT_APPEND_TO = "k";
Blockly.Msg.TEXT_APPEND_TOOLTIP = "Doda besedilo k spremenljivki '%1'.";
Blockly.Msg.TEXT_CHANGECASE_HELPURL = "https://github.com/google/blockly/wiki/Text#adjusting-text-case";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_LOWERCASE = "v male črke";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_TITLECASE = "v Velike Začetnice";
Blockly.Msg.TEXT_CHANGECASE_OPERATOR_UPPERCASE = "v VELIKE ČRKE";
Blockly.Msg.TEXT_CHANGECASE_TOOLTIP = "Vrne kopijo besedila v drugi obliki.";
Blockly.Msg.TEXT_CHARAT_FIRST = "vrni prvo črko";
Blockly.Msg.TEXT_CHARAT_FROM_END = "vrni črko št. od konca";
Blockly.Msg.TEXT_CHARAT_FROM_START = "vrni črko št.";
Blockly.Msg.TEXT_CHARAT_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-text";
Blockly.Msg.TEXT_CHARAT_INPUT_INTEXT = "iz besedila";
Blockly.Msg.TEXT_CHARAT_LAST = "vrni zadnjo črko";
Blockly.Msg.TEXT_CHARAT_RANDOM = "vrni naključno črko";
Blockly.Msg.TEXT_CHARAT_TAIL = "";  // untranslated
Blockly.Msg.TEXT_CHARAT_TOOLTIP = "Vrne črko na določenem mestu v besedilu.";
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TOOLTIP = "Doda element k besedilu.";
Blockly.Msg.TEXT_CREATE_JOIN_TITLE_JOIN = "združi";
Blockly.Msg.TEXT_CREATE_JOIN_TOOLTIP = "Doda, odstrani ali spremeni vrstni red elementov tega besedila.";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_END = "do črke št. od konca";
Blockly.Msg.TEXT_GET_SUBSTRING_END_FROM_START = "do črke št.";
Blockly.Msg.TEXT_GET_SUBSTRING_END_LAST = "do zadnje črke";
Blockly.Msg.TEXT_GET_SUBSTRING_HELPURL = "https://github.com/google/blockly/wiki/Text#extracting-a-region-of-text";
Blockly.Msg.TEXT_GET_SUBSTRING_INPUT_IN_TEXT = "iz besedila";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FIRST = "vrni del od prve črke";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_END = "vrni del od črke št. od konca";
Blockly.Msg.TEXT_GET_SUBSTRING_START_FROM_START = "vrni del od črke št.";
Blockly.Msg.TEXT_GET_SUBSTRING_TAIL = "";  // untranslated
Blockly.Msg.TEXT_GET_SUBSTRING_TOOLTIP = "Vrne določen del besedila.";
Blockly.Msg.TEXT_INDEXOF_HELPURL = "https://github.com/google/blockly/wiki/Text#finding-text";
Blockly.Msg.TEXT_INDEXOF_INPUT_INTEXT = "v besedilu";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_FIRST = "najdi prvo pojavitev besedila";
Blockly.Msg.TEXT_INDEXOF_OPERATOR_LAST = "najdi zadnjo pojavitev besedila";
Blockly.Msg.TEXT_INDEXOF_TAIL = "";  // untranslated
Blockly.Msg.TEXT_INDEXOF_TOOLTIP = "Vrne mesto (indeks) prve/zadnje pojavitve drugega besedila v prvem besedilu. Če besedila ne najde, vrne %1.";
Blockly.Msg.TEXT_ISEMPTY_HELPURL = "https://github.com/google/blockly/wiki/Text#checking-for-empty-text";
Blockly.Msg.TEXT_ISEMPTY_TITLE = "%1 je prazno";
Blockly.Msg.TEXT_ISEMPTY_TOOLTIP = "Vrne resnično, če je določeno besedilo prazno.";
Blockly.Msg.TEXT_JOIN_HELPURL = "https://github.com/google/blockly/wiki/Text#text-creation";
Blockly.Msg.TEXT_JOIN_TITLE_CREATEWITH = "ustvari besedilo iz";
Blockly.Msg.TEXT_JOIN_TOOLTIP = "Ustvari besedilo tako, da združi poljubno število elementov.";
Blockly.Msg.TEXT_LENGTH_HELPURL = "https://github.com/google/blockly/wiki/Text#text-modification";
Blockly.Msg.TEXT_LENGTH_TITLE = "dolžina %1";
Blockly.Msg.TEXT_LENGTH_TOOLTIP = "Vrne število črk oz. znakov (vključno s presledki) v določenem besedilu.";
Blockly.Msg.TEXT_PRINT_HELPURL = "https://github.com/google/blockly/wiki/Text#printing-text";
Blockly.Msg.TEXT_PRINT_TITLE = "izpiši %1";
Blockly.Msg.TEXT_PRINT_TOOLTIP = "Izpiše določeno besedilo, število ali drugo vrednost.";
Blockly.Msg.TEXT_PROMPT_HELPURL = "https://github.com/google/blockly/wiki/Text#getting-input-from-the-user";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_NUMBER = "Vpraša uporabnika za vnos števila.";
Blockly.Msg.TEXT_PROMPT_TOOLTIP_TEXT = "Vpraša uporabnika za vnos besedila.";
Blockly.Msg.TEXT_PROMPT_TYPE_NUMBER = "vprašaj za število s sporočilom";
Blockly.Msg.TEXT_PROMPT_TYPE_TEXT = "vprašaj za besedilo s sporočilom";
Blockly.Msg.TEXT_TEXT_HELPURL = "https://en.wikipedia.org/wiki/String_(computer_science)";
Blockly.Msg.TEXT_TEXT_TOOLTIP = "Črka, beseda ali vrstica besedila.";
Blockly.Msg.TEXT_TRIM_HELPURL = "https://github.com/google/blockly/wiki/Text#trimming-removing-spaces";
Blockly.Msg.TEXT_TRIM_OPERATOR_BOTH = "odstrani presledke z obeh strani";
Blockly.Msg.TEXT_TRIM_OPERATOR_LEFT = "odstrani presledke z leve strani";
Blockly.Msg.TEXT_TRIM_OPERATOR_RIGHT = "odstrani presledke z desne strani";
Blockly.Msg.TEXT_TRIM_TOOLTIP = "Vrne kopijo besedila z odstranjenimi presledki z ene ali obeh strani.";
Blockly.Msg.THYMIO_ACTUATOR_COMM = "set IR communication to transmit to";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_COMM_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_COMM_TOOLTIP = "Sets the IR communication value to send";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MIC = "set microphone threshold to";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MIC_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MIC_TOOLTIP = "Sets the microphone threshold";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MOTOR = "set %1 motor speed to %2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MOTOR_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MOTOR_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MOTOR_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_MOTOR_TOOLTIP = "Sets a motor speed on the robot";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_SET_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_SET_TOOLTIP = "Sets an actuator variable on the robot";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_TIMER = "set %1 timer period to %2 milliseconds";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_TIMER_FIRST = "first";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_TIMER_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_TIMER_SECOND = "second";  // untranslated
Blockly.Msg.THYMIO_ACTUATOR_TIMER_TOOLTIP = "Sets a timer period variable on the robot";  // untranslated
Blockly.Msg.THYMIO_ARITHMETIC_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_ARITHMETIC_TOOLTIP = "Computes arithmetic expressions";  // untranslated
Blockly.Msg.THYMIO_BINARY = "%2 binary %1 %3";  // untranslated
Blockly.Msg.THYMIO_BINARY_AND = "and";  // untranslated
Blockly.Msg.THYMIO_BINARY_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_BINARY_LEFT_SHIFT = "left shift";  // untranslated
Blockly.Msg.THYMIO_BINARY_OR = "or";  // untranslated
Blockly.Msg.THYMIO_BINARY_RIGHT_SHIFT = "right shift";  // untranslated
Blockly.Msg.THYMIO_BINARY_TOOLTIP = "Computes binary expressions";  // untranslated
Blockly.Msg.THYMIO_BINARY_XOR = "xor";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED = "%1 button touched";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_BACKWARD = "backward";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_CENTER = "center";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_FORWARD = "forward";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_BUTTON_PRESSED_TOOLTIP = "Checks if a button is pressed";  // untranslated
Blockly.Msg.THYMIO_COMMUNICATION = "%1 IR communication";  // untranslated
Blockly.Msg.THYMIO_COMMUNICATION_DISABLE = "disable";  // untranslated
Blockly.Msg.THYMIO_COMMUNICATION_ENABLE = "enable";  // untranslated
Blockly.Msg.THYMIO_COMMUNICATION_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_COMMUNICATION_TOOLTIP = "Controls the communication feature of the robot";  // untranslated
Blockly.Msg.THYMIO_DECLARE_ARRAY = "declare %1 as array of size %2";  // untranslated
Blockly.Msg.THYMIO_DECLARE_ARRAY_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_DECLARE_ARRAY_TOOLTIP = "Declares an array of a certain size";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON = "on %1 button %2";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_BACKWARD = "backward";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_CENTER = "center";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_FORWARD = "forward";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_PRESS = "touched";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_RELEASE = "released";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_EVENT_BUTTON_TOOLTIP = "React to a button press or release event";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX = "on %1 sensor detecting %2";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_FRONT_LEFT = "front left";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_FRONT_LEFT_MIDDLE = "front left/middle";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_FRONT_MIDDLE = "front middle";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_FRONT_RIGHT = "front right";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_FRONT_RIGHT_MIDDLE = "front right/middle";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND = "on %1 ground sensor detecting %2";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_BLACK = "black";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_NOPROX = "no proximity";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_PROX = "proximity";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_TOOLTIP = "React to a ground proximity event";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_GROUND_WHITE = "white";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_NOPROX = "no proximity";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_PROX = "proximity";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_REAR_LEFT = "rear left";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_REAR_RIGHT = "rear right";  // untranslated
Blockly.Msg.THYMIO_EVENT_PROX_TOOLTIP = "React to a proximity event";  // untranslated
Blockly.Msg.THYMIO_EVENT_RECEIVE = "on %1 received";  // untranslated
Blockly.Msg.THYMIO_EVENT_RECEIVE_COMM = "IR communication";  // untranslated
Blockly.Msg.THYMIO_EVENT_RECEIVE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_RECEIVE_RC = "remote control signal";  // untranslated
Blockly.Msg.THYMIO_EVENT_RECEIVE_TOOLTIP = "React to a receive event";  // untranslated
Blockly.Msg.THYMIO_EVENT_SHOCK = "on shock detected";  // untranslated
Blockly.Msg.THYMIO_EVENT_SHOCK_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_SHOCK_TOOLTIP = "React to a shock event";  // untranslated
Blockly.Msg.THYMIO_EVENT_SOUND = "on sound %1";  // untranslated
Blockly.Msg.THYMIO_EVENT_SOUND_FINISHED = "finished playing";  // untranslated
Blockly.Msg.THYMIO_EVENT_SOUND_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_SOUND_MIC = "intensity above threshold";  // untranslated
Blockly.Msg.THYMIO_EVENT_SOUND_TOOLTIP = "React to a sound event";  // untranslated
Blockly.Msg.THYMIO_EVENT_TIMER = "on %1 timer expired";  // untranslated
Blockly.Msg.THYMIO_EVENT_TIMER_FIRST = "first";  // untranslated
Blockly.Msg.THYMIO_EVENT_TIMER_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_TIMER_SECOND = "second";  // untranslated
Blockly.Msg.THYMIO_EVENT_TIMER_TOOLTIP = "React to an expired timer event";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE = "on %1 updated";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_ACC = "accelerometer";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_BUTTONS = "button values";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_MOTOR = "motor";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_PROX = "proximity sensors";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_TEMPERATURE = "temperature";  // untranslated
Blockly.Msg.THYMIO_EVENT_UPDATE_TOOLTIP = "React to an update event";  // untranslated
Blockly.Msg.THYMIO_FOR_DO = "do";  // untranslated
Blockly.Msg.THYMIO_FOR_FOR = "for";  // untranslated
Blockly.Msg.THYMIO_FOR_FROM = "from";  // untranslated
Blockly.Msg.THYMIO_FOR_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_FOR_TO = "to";  // untranslated
Blockly.Msg.THYMIO_FOR_TOOLTIP = "Counts a variable up from a start to an end value";  // untranslated
Blockly.Msg.THYMIO_GET_ARRAY = "array %1 element %2";  // untranslated
Blockly.Msg.THYMIO_GET_ARRAY_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_GET_ARRAY_TOOLTIP = "Gets the value of an array element";  // untranslated
Blockly.Msg.THYMIO_LED = "set %1 LED to %2";  // untranslated
Blockly.Msg.THYMIO_LED_BOTTOM_LEFT = "bottom left";  // untranslated
Blockly.Msg.THYMIO_LED_BOTTOM_RIGHT = "bottom right";  // untranslated
Blockly.Msg.THYMIO_LED_BUTTON = "set button LEDs to forward %1 right %2 backward %3 left %4";  // untranslated
Blockly.Msg.THYMIO_LED_BUTTON_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_BUTTON_TOOLTIP = "Sets the button LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_CIRCLE = "set circle LEDs to forward %1 forward right %2 right %3 backward right %4 backward %5 backward left %6 left %7 forward left %8";  // untranslated
Blockly.Msg.THYMIO_LED_CIRCLE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_CIRCLE_TOOLTIP = "Sets the circle LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_OFF = "turn off %1";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_BOTTOM_LEFT = "bottom left LED";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_BOTTOM_RIGHT = "bottom right LED";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_BUTTONS = "button LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_CIRCLE = "circle LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_MICROPHONE = "microphone LED";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_PROX_H = "horizontal proximity LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_PROX_V = "ground proximity LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_RC = "remote control LED";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_TEMPERATURE = "temperature LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_TOOLTIP = "Turns off a LED";  // untranslated
Blockly.Msg.THYMIO_LED_OFF_TOP = "top LED";  // untranslated
Blockly.Msg.THYMIO_LED_PROX = "set horizontal proximity LEDs to front left %1 front left/middle %2 front middle/left %3 front middle/right %4 front right/middle %5 front right %6 rear left %7 rear right %8";  // untranslated
Blockly.Msg.THYMIO_LED_PROX_GROUND = "set ground proximity LEDs to left %1 right %2";  // untranslated
Blockly.Msg.THYMIO_LED_PROX_GROUND_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_PROX_GROUND_TOOLTIP = "Sets the ground proximity LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_PROX_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_PROX_TOOLTIP = "Sets the horizontal proximity LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_RC_SOUND = "set %1 LED to %2";  // untranslated
Blockly.Msg.THYMIO_LED_RC_SOUND_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_RC_SOUND_RC = "remote control";  // untranslated
Blockly.Msg.THYMIO_LED_RC_SOUND_SOUND = "microphone";  // untranslated
Blockly.Msg.THYMIO_LED_RC_SOUND_TOOLTIP = "Sets the remote control and sound LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_RGB = "set %1 LED to red %2 green %3 blue %4";  // untranslated
Blockly.Msg.THYMIO_LED_RGB_BOTTOM_LEFT = "bottom left";  // untranslated
Blockly.Msg.THYMIO_LED_RGB_BOTTOM_RIGHT = "bottom right";  // untranslated
Blockly.Msg.THYMIO_LED_RGB_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_RGB_TOOLTIP = "Sets a LED to a specified color by RGB values";  // untranslated
Blockly.Msg.THYMIO_LED_RGB_TOP = "top";  // untranslated
Blockly.Msg.THYMIO_LED_TEMPERATURE = "set temperature LEDs to red %1 blue %2";  // untranslated
Blockly.Msg.THYMIO_LED_TEMPERATURE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_LED_TEMPERATURE_TOOLTIP = "Sets the temperature LEDs";  // untranslated
Blockly.Msg.THYMIO_LED_TOOLTIP = "Sets a LED to a specified color";  // untranslated
Blockly.Msg.THYMIO_LED_TOP = "top";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START = "start %1 with speed %2";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_BACKWARD = "driving backward";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_FORWARD = "driving forward";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_SPINCCW = "spinning counterclockwise";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_SPINCW = "spinning clockwise";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_TOOLTIP = "Starts the motors";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_TURNBACKWARDLEFT = "turning backward left";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_TURNBACKWARDRIGHT = "turning backward right";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_TURNLEFT = "turning left";  // untranslated
Blockly.Msg.THYMIO_MOTORS_START_TURNRIGHT = "turning right";  // untranslated
Blockly.Msg.THYMIO_MOTORS_STOP = "stop motors";  // untranslated
Blockly.Msg.THYMIO_MOTORS_STOP_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_MOTORS_STOP_TOOLTIP = "Stops the motors";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK = "%1 sensor detecting %2";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_FRONT_LEFT = "front left";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_FRONT_LEFT_MIDDLE = "front left/middle";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_FRONT_MIDDLE = "front middle";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_FRONT_RIGHT = "front right";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_FRONT_RIGHT_MIDDLE = "front right/middle";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_NOPROX = "no proximity";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_PROX = "proximity";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_REAR_LEFT = "rear left";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_REAR_RIGHT = "rear right";  // untranslated
Blockly.Msg.THYMIO_PROX_CHECK_TOOLTIP = "Checks if a proximity sensor is blocked";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK = "%1 ground sensor detecting %2";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_BLACK = "black";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_NOPROX = "no proximity";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_PROX = "proximity";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_TOOLTIP = "Checks if a proximity sensor is blocked";  // untranslated
Blockly.Msg.THYMIO_PROX_GROUND_CHECK_WHITE = "white";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC = "accelerometer %1 value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC_TOOLTIP = "Retrieves a accelerometer sensor value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC_X = "x";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC_Y = "y";  // untranslated
Blockly.Msg.THYMIO_SENSOR_ACC_Z = "z";  // untranslated
Blockly.Msg.THYMIO_SENSOR_COMM = "received IR communication value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_COMM_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_COMM_TOOLTIP = "Retrieves the received IR communication value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MIC = "microphone intensity value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MIC_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MIC_TOOLTIP = "Retrieves the microphone intensity value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MOTOR = "%1 motor speed";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MOTOR_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MOTOR_LEFT = "left";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MOTOR_RIGHT = "right";  // untranslated
Blockly.Msg.THYMIO_SENSOR_MOTOR_TOOLTIP = "Retrieves the speed of a motor";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX = "%1 proximity sensor closeness";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_FRONT_LEFT = "front left";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_FRONT_LEFT_MIDDLE = "front left/middle";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_FRONT_MIDDLE = "front middle";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_FRONT_RIGHT = "front right";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_FRONT_RIGHT_MIDDLE = "front right/middle";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_GROUND_LEFT = "left ground";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_GROUND_RIGHT = "right ground";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_REAR_LEFT = "rear left";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_REAR_RIGHT = "rear right";  // untranslated
Blockly.Msg.THYMIO_SENSOR_PROX_TOOLTIP = "Retrieves the closeness of a proximity sensor";  // untranslated
Blockly.Msg.THYMIO_SENSOR_RC = "received remote control %1 value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_RC_ADDRESS = "address";  // untranslated
Blockly.Msg.THYMIO_SENSOR_RC_COMMAND = "command";  // untranslated
Blockly.Msg.THYMIO_SENSOR_RC_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_RC_TOOLTIP = "Retrieves a remote control sensor value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_TEMPERATURE = "temperature sensor value";  // untranslated
Blockly.Msg.THYMIO_SENSOR_TEMPERATURE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SENSOR_TEMPERATURE_TOOLTIP = "Retrieves the temperature sensor value";  // untranslated
Blockly.Msg.THYMIO_SET_ARRAY = "set array %1 element %2 to %3";  // untranslated
Blockly.Msg.THYMIO_SET_ARRAY_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SET_ARRAY_TOOLTIP = "Sets the value of an array element";  // untranslated
Blockly.Msg.THYMIO_SOUND_NOTE = "play %1 Hz note for %2 / 60 seconds";  // untranslated
Blockly.Msg.THYMIO_SOUND_NOTE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SOUND_NOTE_TOOLTIP = "Plays a note of a frequency for a duration";  // untranslated
Blockly.Msg.THYMIO_SOUND_STOP = "stop playing sound";  // untranslated
Blockly.Msg.THYMIO_SOUND_STOP_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SOUND_STOP_TOOLTIP = "Stops playing sound";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM = "play %1 sound";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_ARROW = "arrow";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_CENTRAL = "central";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_COLLISION = "collision";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_SCARY = "scary";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_SHUTDOWN = "shutdown";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_STARTUP = "startup";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_TARGET_DETECTED = "target detected";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_TARGET_FRIENDLY = "target friendly";  // untranslated
Blockly.Msg.THYMIO_SOUND_SYSTEM_TOOLTIP = "Plays a system sound";  // untranslated
Blockly.Msg.THYMIO_SUBROUTINE_DEFINE_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_SUBROUTINE_DEFINE_SUBROUTINE = "subroutine";  // untranslated
Blockly.Msg.THYMIO_SUBROUTINE_DEFINE_TOOLTIP = "Defines subroutines";  // untranslated
Blockly.Msg.THYMIO_UNARY_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_UNARY_TOOLTIP = "Performs unary operations";  // untranslated
Blockly.Msg.THYMIO_UNNARY = "%1 %2";  // untranslated
Blockly.Msg.THYMIO_UNNARY_ABSOLUTE = "absolute";  // untranslated
Blockly.Msg.THYMIO_UNNARY_BINARY_NOT = "binary not";  // untranslated
Blockly.Msg.THYMIO_UNNARY_NEGATIVE = "negative";  // untranslated
Blockly.Msg.THYMIO_VARIABLE_SET = "set %1 to %2";  // untranslated
Blockly.Msg.THYMIO_WHEN_DO = "do";  // untranslated
Blockly.Msg.THYMIO_WHEN_HELPURL = "https://www.thymio.org/en:thymiotutorielp2";  // untranslated
Blockly.Msg.THYMIO_WHEN_TOOLTIP = "Check for a change of condition";  // untranslated
Blockly.Msg.THYMIO_WHEN_WHEN = "when";  // untranslated
Blockly.Msg.TODAY = "Danes";
Blockly.Msg.UNDO = "Razveljavi";
Blockly.Msg.VARIABLES_DEFAULT_NAME = "element";
Blockly.Msg.VARIABLES_GET_CREATE_SET = "Ustvari 'nastavi %1'";
Blockly.Msg.VARIABLES_GET_HELPURL = "https://github.com/google/blockly/wiki/Variables#get";
Blockly.Msg.VARIABLES_GET_TOOLTIP = "Vrne vrednost spremenljivke.";
Blockly.Msg.VARIABLES_SET = "nastavi %1 na %2";
Blockly.Msg.VARIABLES_SET_CREATE_GET = "Ustvari 'vrni %1'";
Blockly.Msg.VARIABLES_SET_HELPURL = "https://github.com/google/blockly/wiki/Variables#set";
Blockly.Msg.VARIABLES_SET_TOOLTIP = "Nastavi, da je vrednost spremenljivke enaka vnosu.";
Blockly.Msg.VARIABLE_ALREADY_EXISTS = "Spremenljivka »%1« že obstaja.";
Blockly.Msg.PROCEDURES_DEFRETURN_TITLE = Blockly.Msg.PROCEDURES_DEFNORETURN_TITLE;
Blockly.Msg.CONTROLS_IF_IF_TITLE_IF = Blockly.Msg.CONTROLS_IF_MSG_IF;
Blockly.Msg.CONTROLS_WHILEUNTIL_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_MSG_THEN = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.CONTROLS_IF_ELSE_TITLE_ELSE = Blockly.Msg.CONTROLS_IF_MSG_ELSE;
Blockly.Msg.PROCEDURES_DEFRETURN_PROCEDURE = Blockly.Msg.PROCEDURES_DEFNORETURN_PROCEDURE;
Blockly.Msg.LISTS_GET_SUBLIST_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.LISTS_GET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.MATH_CHANGE_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.PROCEDURES_DEFRETURN_DO = Blockly.Msg.PROCEDURES_DEFNORETURN_DO;
Blockly.Msg.CONTROLS_IF_ELSEIF_TITLE_ELSEIF = Blockly.Msg.CONTROLS_IF_MSG_ELSEIF;
Blockly.Msg.LISTS_GET_INDEX_HELPURL = Blockly.Msg.LISTS_INDEX_OF_HELPURL;
Blockly.Msg.CONTROLS_FOREACH_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_SET_INDEX_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.CONTROLS_FOR_INPUT_DO = Blockly.Msg.CONTROLS_REPEAT_INPUT_DO;
Blockly.Msg.LISTS_CREATE_WITH_ITEM_TITLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_APPEND_VARIABLE = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.TEXT_CREATE_JOIN_ITEM_TITLE_ITEM = Blockly.Msg.VARIABLES_DEFAULT_NAME;
Blockly.Msg.LISTS_INDEX_OF_INPUT_IN_LIST = Blockly.Msg.LISTS_INLIST;
Blockly.Msg.PROCEDURES_DEFRETURN_COMMENT = Blockly.Msg.PROCEDURES_DEFNORETURN_COMMENT;